server:
  port: 7001
eureka:
  instance:
    hostname: eureka7001.com  #eureka服务端的实例名称
  client:
    # false 表示不向注册中心注册自己
    register-with-eureka: false
    # false 表示自己端就是 注册中心，自己的职责就是 维护服务实例，并不需要去检索服务
    fetch-registry: false
    service-url:
      #设置与Eureka Server 交互的地址查询服务和注册服务 都需要依赖这个地址。
      #defaultZone: http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka
      #单机 - 指向 自己
      defaultZone: http://eureka7001.com:7001/eureka
  server:
    # 关闭 自我保护机制，保证不可用服务被及时剔除
    #enable-self-preservation: false
    eviction-interval-timer-in-ms: 2000