server:
  port: 8802


spring:
  application:
    name: cloud-stream-consumer
  cloud:
    stream:
      binders: #在此处配置要绑定的rabbitmq的服务信息：
        defaultRabbit: # 表示 定义的名称，用于 binding 整合
          type: rabbit # 消息组件类型
          environment: # 设置 rabbitmq 的相关的环境配置
            spring:
              rabbitmq:
                host: 10.211.55.6
                port: 5672
                username: admin
                password: admin
      bindings: # 服务的整合处理
        input: # 这个名字是一个通道的名称
          destination: studyExchange  # 表示 要使用的 Exchange 名称定义
          content-type: application/json # 设置消息类型，本次是json；若文本则设置 text/plain
          binder: defaultRabbit # 设置 要绑定的消息服务的具体设置
          group: sonyanA
  rabbitmq:
    host: 10.211.55.6
    port: 5672
    username: admin
    password: admin


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7001/eureka #单机版
  instance:
    instance-id: receiver8802
    prefer-ip-address: true   #访问路径可以显示IP地址
    #Eureka 客户端向 服务端 发送心跳的时间间隔 单位：秒（默认是30秒）
    lease-renewal-interval-in-seconds: 2
    #Eureka 服务端 在接收到 最后一次心跳后 等待时间上限，单位秒 默认90秒，超时将剔除服务
    lease-expiration-duration-in-seconds: 5