server:
  port: 80

spring:
  application:
    name: cloud-order-openfeign-hystrix-service

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
       defaultZone: http://eureka7001.com:7001/eureka  #单机版
      #defaultZone: http://localhost:7001/eureka,http://localhost:7002/eureka,,http://localhost:7003/eureka



feign:
  hystrix:
    enabled: true



##设置feign 客户端超时时间（openfeign默认支持ribbon）
#ribbon:
#  #指的是建立连接所用的时间，适用于网络状况正常的情况下,两端连接所用的时间
#  ReadTimeout: 5000
#  #指的是建立连接后从服务器读取到可用资源所用的时间
#  ConnectTimeout: 5000
#
#
#logging:
#  level:
#    # feign 日志 以什么级别监控哪个接口
#    com.sonyan.springcloud.service.PaymentFeignService: debug